server:
    port: 2222

##############
#  MYSQL  #
##############
#spring:
#    datasource:
#        driver-class-name:
#            com.mysql.cj.jdbc.Driver
#        url:
#            jdbc:mysql://localhost:3306/spring_db?useTimezone=true&serverTimezone=UTC
#        username:
#            springuser
#        password:
#            1234


##############
#  POSTGRES  #
##############
spring:
    datasource:
        url: jdbc:postgresql://ec2-18-235-97-230.compute-1.amazonaws.com:5432/dbaiokv5f2vrst?useTimezone=true&serverTimezone=UTC
        username: SPRING_DATASOURCE_USERNAME
        password: SPRING_DATASOURCE_PASSWORD
        driver-class-name: org.postgresql.Driver