server:
    port: 2222

##############
#  MYSQL  #
##############
# spring:
#    datasource:
#        driver-class-name: com.mysql.cj.jdbc.Driver
#        url: jdbc:mysql://localhost:3306/spring_db?useTimezone=true&serverTimezone=UTC
#        username: springuser
#        password: Spring@1234


##############
#  POSTGRES  #
##############
spring:
    datasource:
        url: URL
        username: SPRING_DATASOURCE_USERNAME
        password: SPRING_DATASOURCE_PASSWORD
        driver-class-name: org.postgresql.Driver